name: Versioner
on:
 push:
    branches: [ master ]
jobs:
  versionerr:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup git config
      run: |
        git config user.name "autoversioner"
        git config user.email "autoversioner@softitlan.mx"
    - name: Autoversion
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
      # - run: npm install
      # - run: npm run versioner
    - name: commit
      run: |
        bash versioner.sh
