name: Deploy
on:
 push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Package
          run: |
            git log -n 2
            version=`git log -n 2`
            echo $version > version.txt
            tail -c 6 version.txt
            folderName=`tail -c 6 version.txt`
            mkdir $folderName
            ls -l
            cp -r files/* $folderName/
            rm -r version.txt
            git push origin master