name: Versioner
on:
 push:
    branches: [ master ]
jobs:
  versioner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup git config
      run: |
        git config user.name "autoversioner"
        git config user.email "autoversioner@softitlan.mx"

    - name: Autoversion
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    # - run: npm install
    # - run: npm run versioner
    - name: commit
      run: |
        ls
        echo `git log --author="autoversioner" -n 1` > version.txt
        mkdir `tail -c 6 version.txt`
        cp -r files/* `tail -c 6 version.txt`/
        ls
        git push origin master
