name: Deploy
on:
  push: 
    branches:
    - master 
  workflow_dispatch:
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Package
          run: |
            git log -n 1
  
